spring:
  application.name: backend

  r2dbc:
    url: r2dbc:h2:mem:///taskdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
openai:
  api:
    key: "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"

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc: DEBUG

server:
  port: 8000
