spring:
  application.name: backend

  r2dbc:
    url: ${db-host}
    username: ${db-user}
    password: ${db-password}

application:
  jwt:
    secret: ${jwt-secret}
    access-token-expiration: 21600 # 60 * 60 * 6 (6 hours)
    refresh-token-expiration: 2592000 # 60 * 60 * 24 * 30 (30 days)

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc: DEBUG

server:
  port: 8000
