spring:
  application.name: backend
  r2dbc:
    url: ${db-host}
    username: ${db-user}
    password: ${db-password}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${redis-host:localhost}
      port: ${redis-port:6379}

application:
  jwt:
    secret: ${jwt-secret}
    access-token-expiration: 21600 # 60 * 60 * 6 (6 hours)
    refresh-token-expiration: 2592000 # 60 * 60 * 24 * 30 (30 days)

app:
  s3:
    bucket-name: ${s3-bucket-name}
    base-url: ${s3-base-url}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    io.r2dbc: DEBUG

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "HEAD"
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "PATCH"
  allowed-headers:
    - "*"

server:
  port: 8000
