openapi: 3.1.0
info:
  title: BOS API documentation
  description: |
    내꿈은건물주  API 문서

  version: 0.0.1-SNAPSHOT
  contact: {}
tags:
  - name: auth
  - name: user
paths:
  /auth/sign-in:
    post:
      operationId: signIn
      summary: 회원 로그인
      tags:
        - auth
      description: |-
        # 로그인
      requestBody:
        $ref: "#/components/requestBodies/SignInRequestSpec"
      responses:
        "200":
          $ref: "#/components/responses/SignInSuccessResponseSpec"
        "400":
          description: |-
            (WIP) 로그인 요청 실패

            에러 응답 정의하며 구체화 예정

            에러 케이스 (확정 X)
            - 입력값 validation (Violations) - 로직 타지 않음 (입력값만 검증)
            - oauth 로그인의 경우 로그인 실패 케이스 (UnSignedUserError) -> 회원가입으로 리디렉션 (로그인시 전달한 인증정보(providerId 등 반환)
            - 로그인 로직중 발생한 에러 (에러명 미정의)

          content:
            application/json:
              schema:
                properties:
                  message:
                    type: object
        "500":
          description: 서버 오류
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: number
                    example: 500
                  message:
                    type: string
                    example: Internal Server Error
  /auth/sign-up:
    post:
      operationId: signUp
      summary: 회원 가입
      tags:
        - auth
      description: |-
        # 회원가입
      requestBody:
        $ref: "#/components/requestBodies/SignUpRequestSpec"
      responses:
        "201":
          $ref: "#/components/responses/SignUpCreatedResponseSpec"
        "400":
          description: |-
            (WIP) 로그인 요청 실패

            에러 응답 정의하며 구체화 예정

            에러 케이스 (확정 X)
            - 입력값 validation (Violations) - 로직 타지 않음 (입력값만 검증)
            - 회원가입 로직중 발생한 에러 (에러명 미정의)

          content:
            application/json:
              schema:
                properties:
                  message:
                    type: object
        "500":
          $ref: "#/components/responses/InternalServerErrorResponseSpec"
  /auth/check-email:
    get:
      tags:
        - auth
      operationId: checkEmail
      summary: 이메일 가입 여부 확인
      description: 입력한 이메일이 이미 가입된 사용자 계정인지 확인합니다.
      parameters:
        - name: email
          in: query
          description: 확인할 이메일 주소
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: |-
            이메일 가입 여부 반환

            해당 이메일로 가입이 되어있는지, 가입되어 있다면 어떤 로그인타입(이메일 인증, sns 인증)인지 반환합니다.

            이메일이 존재하는 경우, `exists` 필드가 true로 설정되고, `provider` 필드에는 해당 이메일의 로그인 타입이 포함됩니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  isExist:
                    type: boolean
                    description: 이메일이 이미 가입된 경우 true, 그렇지 않은 경우 false
                  provider:
                    $ref: "#/components/schemas/Provider"
                example:
                  email: abc@abc.com
                  exists: true
                  provider: bos
        "400":
          description: 잘못된 이메일 형식 또는 누락된 파라미터
        "404":
          description: |-
            해당 이메일로 가입되지 않은 유저가 있는 경우
  /auth/email-verification:
    post:
      tags:
        - auth
      operationId: requestEmailVerification
      summary: "이메일 인증 요청"
      description: |-
        이메일 인증 요청을 보내고, 인증 코드가 포함된 이메일을 발송합니다.

        이메일 인증은 회원가입시 이메일 인증을 위해 사용됩니다.

        ## Request Body
        - email: 인증을 요청할 이메일 주소
        - type: 인증 타입 (signup, password-reset)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: "#/components/schemas/Email"
                type:
                  type: string
                  enum:
                    - SIGNUP
                    - PASSWORD_RESET
      responses:
        "204":
          description: |-
            이메일 요청이 성공적으로 요청되면 응답 바디 없이 204만 반환합니다.
        "409":
          description: |-
            - `EMAIL_DUPLICATE`: 가입된 이메일이 있는 경우
            - `EMAIL_VERIFICATION_TYPE_NOT_SUPPORTED`: 지원하지 않는 인증 타입
        "400":
          description: |-
            - `USER_NOT_FOUND`: 사용자를 찾을 수 없는 경우
            - `INVALID_PARAMETER`: type 값이 지원하지 않는 값인 경우
  /auth/email-verification/verify-code:
    post:
      tags:
        - auth
      operationId: verifyEmailCode
      summary: "이메일 인증 코드 검증"
      description: |-
        이메일 인증 코드 검증을 수행합니다.

        ## Request Body
        - email: 인증을 요청한 이메일 주소
        - code: 검증할 인증 코드
        - type: 인증 타입 (signup, password-reset)

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: "#/components/schemas/Email"
                code:
                  type: string
                  description: 인증 코드
                type:
                  type: string
                  enum:
                    - SIGNUP
                    - PASSWORD_RESET
      responses:
        "204":
          description: |-
            - 이메일 요청이 성공적으로 요청되면 응답 바디 없이 204만 반환합니다.

        "400":
          description: |-
            - `EMAIL_VERIFICATION_CODE_MISMATCH`: 이메일 인증 코드가 일치하지 않는 경우
            - `EMAIL_VERIFICATION_CODE_EXPIRED`: 이메일 인증 코드가 만료된 경우

  /auth/email-verification/resend:
    post:
      tags:
        - auth
      operationId: resendEmailVerification
      summary: "이메일 인증 코드 재전송"
      description: |-
        이메일 인증 코드 재전송을 수행합니다.

        ## Request Body
        - email: 인증을 요청한 이메일 주소
        - type: 인증 타입 (signup, password-reset)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: "#/components/schemas/Email"
                type:
                  type: string
                  enum:
                    - SIGNUP
                    - PASSWORD_RESET
      responses:
        "204":
          description: |-
            - 이메일 요청이 성공적으로 요청되면 응답 바디 없이 204만 반환합니다.

        "429":
          description: |-
            - `TOO_MANY_REQUESTS`: 60초 이내에 요청했을 경우
  /users/me:
    get:
      tags:
        - user
      operationId: getMe
      summary: "내 정보 조회"
      description: |-
          유효한 액세스토큰으로 조회한 유저의 프로필 정보 조회
      security:
          - BearerAuth: []
      responses:
        "200":
          $ref: "#/components/responses/GetMeResponseSpec"
        "401":
          description: 인증 실패
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BaseProblemDetails"
    patch:
      tags:
        - user
      operationId: updateMe
      summary: "내 정보 수정"
      description: |-
        유저의 프로필 정보를 수정합니다.
        - 닉네임, 캐릭터 컴포넌트, 홈 타입, 알림 허용 여부, 마케팅 동의 여부를 수정할 수 있습니다.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserProfileRequest"
      responses:
        "200":
          $ref: "#/components/responses/GetMeResponseSpec"
        "400":
          $ref: "#/components/responses/BadRequestResponseSpec"
        "401":
          description: 인증 실패
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/BaseProblemDetails"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BaseProblemDetails:
      type: object
      required:
        - type
        - title
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
    BaseUser:
      type: object
      properties:
        providerId:
          type: string
          description: 소셜로그인을 하면서 provider 로부터 받은 id 를 저장합니다.
          example: "1238923918302390"
        provider:
          $ref: "#/components/schemas/Provider"
        email:
          $ref: "#/components/schemas/Email"
        password:
          type: string
          example: abcdefg12345
          description: |-
            이메일 계정인 경우에만 사용합니다. 소셜로그인의 경우 `null`

            클라이언트 인증이 된 상태로 넘어와야 합니다 (AES-256)
    Gender:
      type: string
      enum:
        - M
        - F
    SignUpRequest:
      required:
        - provider
        - email
        - termsAgreements
      allOf:
        - $ref: "#/components/schemas/BaseUser"
        - type: object
          properties:
            providerAccessToken:
              description: |-
                소셜로그인 제공자로부터 받은 access token 입니다. (KAKAO 등)
              $ref: "#/components/schemas/JwtToken"
            termsAgreements:
              description: |-
                유저의 약관 동의 정보
                약관 동의는 `termsAgreements` 에서 `termId` 와 `isAgree` 를 통해 약관 동의 여부를 나타냅니다.
              type: array
              items:
                type: object
                required:
                  - termId
                  - isAgree
                properties:
                  termId:
                    type: integer
                    format: int64
                    description: 약관 아이디
                  isAgree:
                    type: boolean
                    description: 약관 동의 여부
    CharacterAsset:
      type: object
      properties:
        key:
          type: string
          description: 캐릭터 컴포넌트의 키
          example: "FACE_TYPE_1"
        uri:
          type: string
          format: uri
          description: 캐릭터 컴포넌트의 이미지 URI
          example: "https://example.com/face_type_1.svg"
    CharacterComponents:
      type: object
      properties:
        faceShape:
          $ref: "#/components/schemas/CharacterAsset"
        hand:
          $ref: "#/components/schemas/CharacterAsset"
        skinColor:
          type: string
          description: 피부색
          example: #FFDBAC
        frontHair:
          $ref: "#/components/schemas/CharacterAsset"
        backHair:
          $ref: "#/components/schemas/CharacterAsset"
        eyes:
          $ref: "#/components/schemas/CharacterAsset"
        mouth:
          $ref: "#/components/schemas/CharacterAsset"
    UpdateUserProfileRequest:
      type: object
      properties:
        nickname:
          type: string
          description: 유저의 닉네임
          example: "홍길동"
        characterComponents:
          $ref: "#/components/schemas/CharacterComponents"
        homeType:
          type: string
          example: "HOME_TYPE_1"
        isNotificationAllowed:
          type: boolean
          description: 유저가 알림을 허용하는지 여부
          example: true
        isMarketingAgreed:
          type: boolean
          description: 유저가 마케팅 수신에 동의하는지 여부
          example: true
    UserProfileResponse:
      type: object
      required:
        - id
        - nickname
        - characterComponents
        - homeType
        - isNotificationAllowed
        - isMarketingAgreed
      properties:
        id:
          type: integer
          format: int64
          description: 유저 아이디
          example: 15423
        nickname:
          type: string
          description: 유저의 닉네임
          example: "홍길동"
        characterComponents:
          $ref: "#/components/schemas/CharacterComponents"
        homeType:
          type: string
          example: "HOME_TYPE_1"
        isNotificationAllowed:
          type: boolean
          description: |-
              유저가 알림을 허용하는지 여부
          example: true
        isMarketingAgreed:
          type: boolean
          description: |-
              유저가 마케팅 수신에 동의하는지 여부
          example: true
    CommonSignResponseBody:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          $ref: "#/components/schemas/JwtToken"
        refreshToken:
          $ref: "#/components/schemas/JwtToken"
    #    SignUpSuccessResponseBody:
    #      type: object
    #      properties:
    #        accessToken:
    #          $ref: "#/components/schemas/JwtToken"
    #        refreshToken:
    #          $ref: "#/components/schemas/JwtToken"
    #    SignInResponse:
    #      type: object
    #      properties:
    #        accessToken:
    #          $ref: "#/components/schemas/JwtToken"
    #        refreshToken:
    #          $ref: "#/components/schemas/JwtToken"
    SignInRequest:
      type: object
      required:
        - provider
        - email
      properties:
        providerId:
          type: string
          description: |-
            인증 제공자로부터 제공받은 유저의 고유값을 입력합니다.

            `EMAIL`의 경우에는 `null` 처리합니다.
          example: "1238923918302390"
        provider:
          $ref: "#/components/schemas/Provider"
        email:
          $ref: "#/components/schemas/Email"
        password:
          type: string
          description: |-
            이메일 계정인 경우에만 사용합니다. 소셜로그인의 경우 `null`
        providerAccessToken:
          description: |-
            소셜로그인 제공자로부터 받은 access token 입니다. (KAKAO 등)
          $ref: "#/components/schemas/JwtToken"
    GetMeBase:
      type: object
    Address:
      type: object
      properties:
        postcode:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        detailAddress:
          type: string
          nullable: true
    JwtToken:
      type: string
      format: jwt
      example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEsInJvbGVOYW1lIjoidXNlciIsImlhdCI6MTYyNDk2MTgzNSwiZXhwIjoxNjI1MzIxODM1LCJpc3MiOiJjaGFib3RwbGF0Zm9ybV9pc3MhIn0.NdBnF65ukwxuLtpPriDXQ--2Tn--7WAPnyz29T9_6s4
    Provider:
      type: string
      description: 인증 제공자
      enum:
        - KAKAO
        - BOS
      example: KAKAO
    Email:
      type: string
      format: email
      description: email 주소
      example: abc@abc.com
    PhoneNumber:
      type: string
      pattern: '^010-\d{4}-\d{4}$'
      description: 대한민국 휴대폰 번호 형식, 010-XXXX-XXXX
      example: "010-1234-5678"
    AlimAgree:
      type: object
      properties:
        sms_yn:
          type: string
        app_yn:
          type: string
        tm_yn:
          type: string
        email_yn:
          type: string
    AlimAgreeRequest:
      required:
        - sms_yn
        - app_yn
        - tm_yn
        - email_yn
      allOf:
        - $ref: "#/components/schemas/AlimAgree"
    AlimAgreeResponse:
      properties:
        data:
          allOf:
            - $ref: "#/components/schemas/AlimAgree"
            - properties:
                marketingAgreeUpdatedDate:
                  type: string
                  format: date-time
    Agreement:
      type: object
      required:
        - id
        - name
        - contentUri
        - isRequired
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          format: int64
          description: 아이디
        name:
          type: string
          description: 제목
          example: 이용약관
        contentUri:
          type: string
          format: uri
          description: 약관 notion link
        isRequired:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    AccountAgreement:
      type: object
      required:
        - agreementId
        - agreementName
        - agreedAt
      properties:
        agreementId:
          type: integer
          format: int64
          description: 약관 아이디
        agreementName:
          type: string
          description: 약관명
          example: 이용약관
        agreedAt:
          type: string
          nullable: true
          format: date-time
          description: |-
            약관 동의 일시, `null`인경우 동의하지 않은 상태
          example: "2025-02-01T00:00:00Z"
    AccountAgreementItem:
      type: object
      required:
        - agreementId
        - isAgree
      properties:
        agreementId:
          type: integer
          format: int64
          description: 약관 아이디
        isAgree:
          type: boolean
          description: 동의 여부
    BosAuthDetail:
      type: object
      required:
        - isEmailVerified
        - email
      properties:
        isEmailVerified:
          type: boolean
        email:
          $ref: "#/components/schemas/Email"
    KakaoAuthDetail:
      type: object
      required:
        - providerId
        - email
      properties:
        providerId:
          type: string
        email:
          $ref: "#/components/schemas/Email"
    AppleAuthDetail:
      type: object
      description: |-
        애플의 경우 사용자의 보안 조치에 따라 사용자의 원 이메일을 반환하지 않고 릴레에 이메일을 반환할 수 있습니다.
      required:
        - providerId
        - relayEmail
      properties:
        providerId:
          type: string
        relayEmail:
          $ref: "#/components/schemas/Email"

  requestBodies:
    SignUpRequestSpec:
      required: true
      description: |-
        회원가입 요청 페이로드

        - providerAccessToken: 소셜로그인 제공자로부터 받은 access token 입니다. (KAKAO 등)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SignUpRequest"
    SignInRequestSpec:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SignInRequest"
  responses:
    NotFoundResponseSpec:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/BaseProblemDetails"
    BadRequestResponseSpec:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/BaseProblemDetails"
    ConflictResponseSpec:
      description: Conflict
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/BaseProblemDetails"
    InternalServerErrorResponseSpec:
      description: 내부 오류가 생겼습니다. 해당 상황 발생 시, 관리자에게 이야기해주세요.
      content:
        application/json:
          schema:
            properties:
              statusCode:
                type: number
                example: 500
              message:
                type: string
                example: Internal Server Error
    SignUpCreatedResponseSpec:
      description: |-
        회원가입 완료시 accessToken, refreshToken 발급
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CommonSignResponseBody"
    SignInSuccessResponseSpec:
      description: 로그인 성공
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CommonSignResponseBody"
    GetMeResponseSpec:
      description: |-
        유효한 액세스토큰으로 조회한 유저 프로필 정보 조회
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UserProfileResponse"
